# Generated by Django 2.1.5 on 2019-04-19 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('pillarType', models.CharField(max_length=10)),
                ('scheduleID', models.IntegerField()),
                ('eventName', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lecturer', models.CharField(max_length=50)),
                ('classEnrolled', models.CharField(max_length=4)),
                ('location', models.CharField(max_length=50)),
                ('isEvent', models.BooleanField(default=False)),
                ('initiatedBy', models.IntegerField()),
            ],
        ),
    ]
