# Generated by Django 2.1.7 on 2019-04-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='isConflicting',
            field=models.BooleanField(default=False),
        ),
    ]
