# Generated by Django 2.1.7 on 2019-04-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='isEvent',
            field=models.BooleanField(default=False),
        ),
    ]
