# Generated by Django 2.1.5 on 2019-04-22 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedule_isconflicting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='eventName',
            new_name='course_Name',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='isConflicting',
            new_name='is_Conflicting',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='isEvent',
            new_name='is_Event',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='start_time',
            new_name='start_Time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='classEnrolled',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='initiatedBy',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='pillarType',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='scheduleID',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='title',
        ),
        migrations.AddField(
            model_name='schedule',
            name='class_Enrolled',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='schedule',
            name='day_Of_Week',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='schedule',
            name='event_Duration',
            field=models.IntegerField(choices=[(1, '15'), (2, '30'), (3, '45'), (4, '60'), (5, '75'), (6, '90'), (7, '105'), (8, '120'), (9, '135'), (10, '150'), (11, '165'), (12, '180')], default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='event_Name',
            field=models.CharField(default='None', max_length=120),
        ),
        migrations.AddField(
            model_name='schedule',
            name='initiated_By',
            field=models.CharField(default='Nobody', max_length=50),
        ),
        migrations.AddField(
            model_name='schedule',
            name='pillar_Type',
            field=models.CharField(choices=[(0, 'ASD'), (1, 'ISTD'), (2, 'EPD'), (3, 'ESD'), (4, 'FRESHMORE'), (5, 'MASTERS'), (6, 'PHD')], default='ISTD', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='location',
            field=models.CharField(choices=[('1', 'any'), ('2', 'Lecture Theatre')], max_length=50),
        ),
    ]
