# Generated by Django 2.1.7 on 2019-03-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='duration',
            field=models.DurationField(default=90),
        ),
    ]
