# Generated by Django 2.1.5 on 2019-04-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20190422_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='location',
            field=models.IntegerField(choices=[('1', 'any'), ('2', 'Lecture Theatre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='pillar_Type',
            field=models.IntegerField(choices=[(0, 'ASD'), (1, 'ISTD'), (2, 'EPD'), (3, 'ESD'), (4, 'FRESHMORE'), (5, 'MASTERS'), (6, 'PHD')], max_length=10),
        ),
    ]
