# Generated by Django 2.1.7 on 2019-04-18 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedule_isevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lecturer', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('isEvent', models.BooleanField(default=False)),
                ('isConflicting', models.BooleanField(default=False)),
            ],
        ),
    ]
