# Generated by Django 2.1.7 on 2019-04-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20190323_1437'),
        ('schedule', '0003_schedule_isevent'),
    ]

    operations = [
    ]
