# Generated by Django 2.1.5 on 2019-04-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20190424_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_Finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_Suggestion',
            field=models.BooleanField(default=False),
        ),
    ]
