# Generated by Django 2.1.5 on 2019-04-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20190424_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='pillar_Type',
            field=models.CharField(choices=[('ASD', 'ASD'), ('ISTD', 'ISTD'), ('EPD', 'EPD'), ('ESD', 'ESD'), ('FRESHMORE', 'FRESHMORE'), ('MASTERS', 'MASTERS'), ('PHD', 'PHD'), ('NONE', 'NONE')], max_length=10),
        ),
    ]
