# Generated by Django 2.1.5 on 2019-04-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20190424_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='isclassconflict',
            field=models.BooleanField(default=False),
        ),
    ]
