# Generated by Django 2.1.5 on 2019-04-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_schedule_isclassconflict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='isclassconflict',
            new_name='is_classconflict',
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_profconflict',
            field=models.BooleanField(default=False),
        ),
    ]
