# Generated by Django 2.1.5 on 2019-04-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phase',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Before First Draft'), (2, 'Drafting'), (3, 'Finalisation')], default=1),
        ),
    ]
