# Generated by Django 2.1.5 on 2019-03-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0002_auto_20190303_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'professor'), (2, 'sutdadmin'), (3, 'coursecoordinators'), (4, 'timetableplanner'), (5, 'student')], default=5)),
                ('subject_code', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=50)),
                ('cohort_size', models.PositiveSmallIntegerField()),
                ('cohort_num', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
