# Generated by Django 2.1.5 on 2019-03-16 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0003_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='userpreferences', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
