# Generated by Django 2.1.5 on 2019-04-08 04:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0003_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='cohort_num',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(16), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='cohort_size',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(800), django.core.validators.MinValueValidator(1)]),
        ),
    ]
