# Generated by Django 2.1.5 on 2019-03-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0004_preferences_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='author',
        ),
    ]
