# Generated by Django 2.1.5 on 2019-04-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0005_auto_20190409_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='day_of_week',
            field=models.CharField(max_length=20),
        ),
    ]
