# Generated by Django 2.1.5 on 2019-03-16 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0005_remove_preferences_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userpref', to=settings.AUTH_USER_MODEL),
        ),
    ]
