# Generated by Django 2.1.5 on 2019-04-09 02:48

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0007_auto_20190409_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='day_of_week',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
