# Generated by Django 2.2 on 2019-04-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='classEnrolled',
            field=models.CharField(default='None', max_length=4),
        ),
        migrations.AddField(
            model_name='schedule',
            name='eventName',
            field=models.CharField(default='None', max_length=120),
        ),
        migrations.AddField(
            model_name='schedule',
            name='initiatedBy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='pillarType',
            field=models.CharField(default='Freshmore', max_length=10),
        ),
        migrations.AddField(
            model_name='schedule',
            name='scheduleID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
