# Generated by Django 2.2 on 2019-04-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='is_Finalized',
        ),
    ]
