# Generated by Django 2.2 on 2019-04-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_schedule_is_finalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_Finalised',
            field=models.BooleanField(default=False),
        ),
    ]
