# Generated by Django 2.2 on 2019-04-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20190419_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='initiatedBy',
            field=models.CharField(default='Nobody', max_length=50),
        ),
    ]
