# Generated by Django 2.2 on 2019-04-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20190419_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='eventDuration',
            field=models.IntegerField(default=0),
        ),
    ]
