# Generated by Django 2.2 on 2019-04-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20190421_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='isConflicting',
            field=models.BooleanField(default=False),
        ),
    ]
