# Generated by Django 2.2 on 2019-04-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_schedule_isconflicting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='classEnrolled',
            new_name='class_Enrolled',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='title',
            new_name='course_Name',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='eventDuration',
            new_name='day_Of_Week',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='eventName',
            new_name='event_Name',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='initiatedBy',
            new_name='initiated_By',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='isConflicting',
            new_name='is_Conflicting',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='isEvent',
            new_name='is_Event',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='pillarType',
            new_name='pillar_Type',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='scheduleID',
            new_name='schedule_ID',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='start_time',
            new_name='start_Time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='event_Duration',
            field=models.IntegerField(default=0),
        ),
    ]
