# Generated by Django 2.2 on 2019-04-22 03:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20190422_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day_Of_Week',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)]),
        ),
    ]
