# Generated by Django 2.2 on 2019-04-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20190422_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='schedule_ID',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='class_Enrolled',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='event_Duration',
            field=models.IntegerField(choices=[(1, '15'), (2, '30'), (3, '45'), (4, '60'), (5, '75'), (6, '90'), (7, '105'), (8, '120'), (9, '135'), (10, '150'), (11, '165'), (12, '180')], default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='location',
            field=models.CharField(choices=[('1', 'any'), ('2', 'Lecture Theatre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='pillar_Type',
            field=models.CharField(choices=[(0, 'ASD'), (1, 'ISTD'), (2, 'EPD'), (3, 'ESD'), (4, 'FRESHMORE'), (5, 'MASTERS'), (6, 'PHD')], max_length=10),
        ),
    ]
