# Generated by Django 2.2 on 2019-04-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20190422_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='class_Enrolled',
            field=models.CharField(default='', max_length=6),
        ),
    ]
