# Generated by Django 2.2 on 2019-04-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_auto_20190422_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='pillar_Type',
            field=models.CharField(choices=[('ASD', 'ASD'), ('ISTD', 'ISTD'), ('EPD', 'EPD'), ('ESD', 'ESD'), ('FRESHMORE', 'FRESHMORE'), ('MASTERS', 'MASTERS'), ('PHD', 'PHD')], max_length=10),
        ),
    ]
