# Generated by Django 2.2 on 2019-04-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20190422_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='event_Duration',
            field=models.IntegerField(choices=[(15, '15'), (30, '30'), (45, '45'), (60, '60'), (75, '75'), (90, '90'), (105, '105'), (120, '120'), (135, '135'), (150, '150'), (165, '165'), (180, '180')], default=0),
        ),
    ]
